Added ARmstrong GO program
codinasion-archive/codinasion-monorepo pull request #4514
Opened 2023-06-23 12:15 UTC by AshitaSingamsetty

2023-06-24 04:12 UTC, hi-Kartik2004 commented
Hi @AshitaSingamsetty, 
firstly thanks for raising the pull request (PR), however, can you link the issue your PR closes in your first comment?

the format is specified below
```bash
closes #issueNumberHere
```

2023-06-25 01:00 UTC, 0ME9A requested changes
Hey @AshitaSingamsetty,

Your code is well written👍 but for next step you have to add this statement in your PR request:-

`closes #(issue-number-here)`

2023-06-25 16:53 UTC, 0ME9A approved these changes

2023-06-25 16:59 UTC, 0ME9A approved these changes

2023-06-25 18:55 UTC, hi-Kartik2004 approved these changes

2023-06-25 18:56 UTC, merged