Create PrintNumberToWordsInIndianNumberingSystem.go
codinasion-archive/codinasion-monorepo pull request #4533
Opened 2023-07-06 16:47 UTC by MadhuS-1605

2023-07-07 02:58 UTC, 0ME9A requested changes

2023-07-07 02:58 UTC, 0ME9A commented on program/program/print-number-to-words-in-indian-numbering-system/program/print-number-to-words-in-indian-numbering-system/PrintNumberToWordsInIndianNumberingSystem.go
Hi @MadhuS-1605, I think there is some error in your code.

```
runtime: goroutine stack exceeds 1000000000-byte limit
fatal error: stack overflow

runtime stack:
runtime.throw(0x4bd86a, 0xe)
        /usr/local/go/src/runtime/panic.go:617 +0x72
runtime.newstack()
        /usr/local/go/src/runtime/stack.go:1041 +0x6f0
runtime.morestack()
        /usr/local/go/src/runtime/asm_amd64.s:429 +0x8f

goroutine 1 [running]:
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024000498)
        /home/main.go:73 +0x5f9 fp=0xc0240003e0 sp=0xc0240003d8 pc=0x489bf9
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc0240005c0)
        /home/main.go:86 +0x231 fp=0xc024000508 sp=0xc0240003e0 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc0240006e8)
        /home/main.go:86 +0x231 fp=0xc024000630 sp=0xc024000508 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024000810)
        /home/main.go:86 +0x231 fp=0xc024000758 sp=0xc024000630 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024000938)
        /home/main.go:86 +0x231 fp=0xc024000880 sp=0xc024000758 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024000a60)
        /home/main.go:86 +0x231 fp=0xc0240009a8 sp=0xc024000880 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024000b88)
        /home/main.go:86 +0x231 fp=0xc024000ad0 sp=0xc0240009a8 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024000cb0)
        /home/main.go:86 +0x231 fp=0xc024000bf8 sp=0xc024000ad0 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024000dd8)
        /home/main.go:86 +0x231 fp=0xc024000d20 sp=0xc024000bf8 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024000f00)
        /home/main.go:86 +0x231 fp=0xc024000e48 sp=0xc024000d20 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024001028)
        /home/main.go:86 +0x231 fp=0xc024000f70 sp=0xc024000e48 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024001150)
        /home/main.go:86 +0x231 fp=0xc024001098 sp=0xc024000f70 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024001278)
        /home/main.go:86 +0x231 fp=0xc0240011c0 sp=0xc024001098 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc0240013a0)
        /home/main.go:86 +0x231 fp=0xc0240012e8 sp=0xc0240011c0 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc0240014c8)
        /home/main.go:86 +0x231 fp=0xc024001410 sp=0xc0240012e8 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc0240015f0)
        /home/main.go:86 +0x231 fp=0xc024001538 sp=0xc024001410 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024001718)
        /home/main.go:86 +0x231 fp=0xc024001660 sp=0xc024001538 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024001840)
        /home/main.go:86 +0x231 fp=0xc024001788 sp=0xc024001660 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024001968)
        /home/main.go:86 +0x231 fp=0xc0240018b0 sp=0xc024001788 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024001a90)
        /home/main.go:86 +0x231 fp=0xc0240019d8 sp=0xc0240018b0 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024001bb8)
        /home/main.go:86 +0x231 fp=0xc024001b00 sp=0xc0240019d8 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024001ce0)
        /home/main.go:86 +0x231 fp=0xc024001c28 sp=0xc024001b00 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024001e08)
        /home/main.go:86 +0x231 fp=0xc024001d50 sp=0xc024001c28 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024001f30)
        /home/main.go:86 +0x231 fp=0xc024001e78 sp=0xc024001d50 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024002058)
        /home/main.go:86 +0x231 fp=0xc024001fa0 sp=0xc024001e78 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024002180)
        /home/main.go:86 +0x231 fp=0xc0240020c8 sp=0xc024001fa0 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc0240022a8)
        /home/main.go:86 +0x231 fp=0xc0240021f0 sp=0xc0240020c8 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc0240023d0)
        /home/main.go:86 +0x231 fp=0xc024002318 sp=0xc0240021f0 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc0240024f8)
        /home/main.go:86 +0x231 fp=0xc024002440 sp=0xc024002318 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024002620)
        /home/main.go:86 +0x231 fp=0xc024002568 sp=0xc024002440 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024002748)
        /home/main.go:86 +0x231 fp=0xc024002690 sp=0xc024002568 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024002870)
        /home/main.go:86 +0x231 fp=0xc0240027b8 sp=0xc024002690 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024002998)
        /home/main.go:86 +0x231 fp=0xc0240028e0 sp=0xc0240027b8 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024002ac0)
        /home/main.go:86 +0x231 fp=0xc024002a08 sp=0xc0240028e0 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024002be8)
        /home/main.go:86 +0x231 fp=0xc024002b30 sp=0xc024002a08 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024002d10)
        /home/main.go:86 +0x231 fp=0xc024002c58 sp=0xc024002b30 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024002e38)
        /home/main.go:86 +0x231 fp=0xc024002d80 sp=0xc024002c58 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024002f60)
        /home/main.go:86 +0x231 fp=0xc024002ea8 sp=0xc024002d80 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024003088)
        /home/main.go:86 +0x231 fp=0xc024002fd0 sp=0xc024002ea8 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc0240031b0)
        /home/main.go:86 +0x231 fp=0xc0240030f8 sp=0xc024002fd0 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc0240032d8)
        /home/main.go:86 +0x231 fp=0xc024003220 sp=0xc0240030f8 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024003400)
        /home/main.go:86 +0x231 fp=0xc024003348 sp=0xc024003220 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024003528)
        /home/main.go:86 +0x231 fp=0xc024003470 sp=0xc024003348 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024003650)
        /home/main.go:86 +0x231 fp=0xc024003598 sp=0xc024003470 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024003778)
        /home/main.go:86 +0x231 fp=0xc0240036c0 sp=0xc024003598 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc0240038a0)
        /home/main.go:86 +0x231 fp=0xc0240037e8 sp=0xc0240036c0 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc0240039c8)
        /home/main.go:86 +0x231 fp=0xc024003910 sp=0xc0240037e8 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024003af0)
        /home/main.go:86 +0x231 fp=0xc024003a38 sp=0xc024003910 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024003c18)
        /home/main.go:86 +0x231 fp=0xc024003b60 sp=0xc024003a38 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024003d40)
        /home/main.go:86 +0x231 fp=0xc024003c88 sp=0xc024003b60 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024003e68)
        /home/main.go:86 +0x231 fp=0xc024003db0 sp=0xc024003c88 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024003f90)
        /home/main.go:86 +0x231 fp=0xc024003ed8 sp=0xc024003db0 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc0240040b8)
        /home/main.go:86 +0x231 fp=0xc024004000 sp=0xc024003ed8 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc0240041e0)
        /home/main.go:86 +0x231 fp=0xc024004128 sp=0xc024004000 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024004308)
        /home/main.go:86 +0x231 fp=0xc024004250 sp=0xc024004128 pc=0x489831
main.convertNumberToWords(0xa, 0xc00007c1e0, 0xc024004430)
        /home/main.go:86 +0x231 fp=0xc024004378 sp=0xc024004250 pc=0x489831
main.convertNumberToW [...]

2023-07-09 06:59 UTC, 0ME9A approved these changes

2023-07-09 07:45 UTC, hi-Kartik2004 approved these changes

2023-07-09 07:45 UTC, merged