Added Go programm to find sum of numbers by recursion
codinasion-archive/codinasion-monorepo pull request #4537
Opened 2023-07-13 16:16 UTC by AshitaSingamsetty

2023-07-13 17:14 UTC, 0ME9A commented
Hi @AshitaSingamsetty, thank you for your contribution! It is much appreciated. However, there is one issue: the reference to the issue ID was not mentioned. For the next step, please add the issue ID as shown below:

Close issue: #issueId

2023-07-13 17:28 UTC, 0ME9A requested changes
I’m glad to see that the code is working as expected! To proceed to the next step, please make sure to add the issue ID in the format shown below:

Close issue: #issueId

2023-07-14 19:23 UTC, 0ME9A approved these changes

2023-07-14 19:25 UTC, 0ME9A commented
Hey @AshitaSingamsetty,

## Note
When submitting a pull request, it is not advisable to use a commenting-only issue-id. Instead, you can reference the issue-id using the # symbol or follow the default template provided.

2023-07-15 17:01 UTC, hi-Kartik2004 approved these changes

2023-07-15 17:01 UTC, merged