Create ReverseWordsInAString.ts
codinasion-archive/codinasion-monorepo pull request #5020
Opened 2024-01-05 18:50 UTC by andrysatko

Write a TypeScript program to reverse words in a string #5018

## 📑 Simple TypeScript program

## 🐞 #5018

Closes #5018

2024-01-05 19:19 UTC, victoriacheng15 requested changes

2024-01-05 19:19 UTC, victoriacheng15 commented on program/program/reverse-words-in-a-string/ReverseWordsInAString.ts
> +return reverseWords(input);
I think you mean to write `console.log(reverseWords(input))` instead of the return?

2024-01-05 20:13 UTC, andrysatko commented on program/program/reverse-words-in-a-string/ReverseWordsInAString.ts
> +return reverseWords(input);
Yeah, you are right, now everything works properly)

2024-01-06 03:26 UTC, anandfresh approved these changes

2024-01-06 05:06 UTC, victoriacheng15 approved these changes

2024-01-06 05:06 UTC, merged