Ternary search implementation
codinasion-archive/codinasion-monorepo pull request #5413
Opened 2024-01-26 15:36 UTC by Parvezkhan0

## 📑 Description

## 🐞 Related Issue

Closes #5129

2024-01-26 16:29 UTC, isyuricunha requested changes
Your implementation of ternary search seems mostly correct. However, there is a small mistake in the "else" part of your loop. When updating the "left" and "right" pointers, you should adjust them based on the comparison with the target value. Here's the corrected code:

```typescript
function ternarySearch(arr: number[], value: number): number {
    let left = 0;
    let right = arr.length - 1;

    while (left <= right) {
        const partitionSize = Math.floor((right - left) / 3);
        const mid1 = left + partitionSize;
        const mid2 = right - partitionSize;

        if (arr[mid1] === value) {
            return mid1;
        }

        if (arr[mid2] === value) {
            return mid2;
        }

        if (value < arr[mid1]) {
            right = mid1 - 1;
        } else if (value > arr[mid2]) {
            left = mid2 + 1;
        } else {
            // Adjust pointers based on the comparison with the target value
            left = mid1 + 1;
            right = mid2 - 1;
        }
    }

    return -1;
}

// Example
const list = [1, 2, 3, 4, 5];
const valueToSearch = 4;

const result = ternarySearch(list, valueToSearch);

console.log(`Output: ${result}`);
```

With this correction, the ternary search implementation should work correctly for the provided example. Having said that, I have checked all the previous commits, and they don't seem to be causing conflicts or altering any file before or after their respective dates.

2024-01-29 17:45 UTC, Parvezkhan0 commented
@isyuricunha Please review my PR again

2024-01-29 20:50 UTC, isyuricunha approved these changes

2024-01-29 20:52 UTC, isyuricunha commented
> @isyuricunha Please review my PR again

I believe you simply copied and pasted what I sent, but that's okay.

I hope you understood what I informed you earlier.

Thank you for contributing.

Take care.

2024-01-30 18:18 UTC, RiteshK-611 approved these changes

2024-01-30 18:18 UTC, merged