Convert Celsius to Kelvin C# Function
codinasion-archive/codinasion-monorepo pull request #5565
Opened 2024-03-23 13:30 UTC by SharliBeicon

## 📑 Description
Convert temperature from Celsius to Kelvin C# Function.

Control of out of bounds temperature exception and applies the formula.

## 🐞 Related Issue

Closes #5544

2024-03-23 17:39 UTC, anandfresh requested changes
@SharliBeicon Can you give an example for executing this class

2024-03-23 18:55 UTC, SharliBeicon commented
@anandfresh Code refactored to make it executable and added comments on how to do it. I hope it works for you! Let me know anything.

2024-03-27 13:54 UTC, anandfresh approved these changes

2024-03-28 06:10 UTC, harshraj8843 approved these changes
Thanks for contributing 🤗

2024-03-28 06:11 UTC, merged