Greeshmanth1 patch 1
codinasion-archive/codinasion-monorepo pull request #5674
Opened 2024-04-24 16:35 UTC by Greeshmanth1

In the original program, the nCr calculation was implemented using the factorial code, which led to repetitive calculations. Here, I have updated the code to be more efficient and eliminate unnecessary calculations.

2024-04-24 17:01 UTC, anandfresh requested changes

2024-04-24 17:01 UTC, anandfresh commented on program/program/calculate-the-combination-of-n-objects-taken-r-at-a-time/calculate_the_combination_of_n_objects_taken_r_at_a_time.py
> +    # ncr    =    n! / (n-r)! * r!     =     n*(n-1)*(n-2)*..*(n-r+1)*(n-r)! / (n-r)! * r!     =     n*(n-1)*(n-2)*..*(n-r+1) / r!
remove unnecessary line of codes instead of commenting

2024-04-26 10:59 UTC, Greeshmanth1 commented on program/program/calculate-the-combination-of-n-objects-taken-r-at-a-time/calculate_the_combination_of_n_objects_taken_r_at_a_time.py
> +    # ncr    =    n! / (n-r)! * r!     =     n*(n-1)*(n-2)*..*(n-r+1)*(n-r)! / (n-r)! * r!     =     n*(n-1)*(n-2)*..*(n-r+1) / r!
Those were not unnecessary lines, those are formula and logic for the code.

2024-05-03 09:40 UTC, anandfresh approved these changes

2024-05-03 20:44 UTC, victoriacheng15 approved these changes

2024-05-03 20:45 UTC, merged